# Generated by Django 4.2.1 on 2023-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pw',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
